import { Meta, StoryObj } from '@storybook/react';
import { IButtonProps } from './Button';
declare const meta: Meta<IButtonProps>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Primary: Story;
export declare const Text: Story;
export declare const Outline: Story;
export declare const Small: Story;
export declare const Meduim: Story;
export declare const Large: Story;
